---
# this fails with 104 errors for some reason.  can't follow redirects?
- name: Download MySQL 5.7.16 RPM bundle (not available GA)
  become: no
  get_url:
      url: "https://downloads.mysql.com/archives/get/file/mysql-5.7.16-1.el7.x86_64.rpm-bundle.tar"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/mysql-5.7.16-1.el7.x86_64.rpm-bundle.tar"
  when: mysql_install and (ansible_distribution == "CentOS")

- name: Untar RPM bundle
  unarchive: 
    src: "{{ansible_user_dir}}/{{base_download_directory}}/mysql-5.7.16-1.el7.x86_64.rpm-bundle.tar"
    dest: "{{ansible_user_dir}}/{{base_download_directory}}/"
    
- name: Install MySQL RPMS
  become: yes
  yum:
      name: "{{ansible_user_dir}}/{{base_download_directory}}/mysql-community-*"
      state: present

# download by hand because of the issue with get_url
- name: Download MySQL Repository Configuration
  become: no
  command: "curl --output {{ansible_user_dir}}/{{base_download_directory}}/mysql57-community-release-el7-9.noarch.rpm http://repo.mysql.com//mysql57-community-release-el7-9.noarch.rpm"
  when: mysql_install and (ansible_distribution == "Redhat")

- name: Install MySQL Repository
  become: yes
  yum:
      name: "{{ansible_user_dir}}/{{base_download_directory}}/mysql57-community-release-el7-9.noarch.rpm"
      state: present
  when: mysql_install and (ansible_distribution == "Redhat")

- name: Install MySQL And Companion Tools
  become: yes
  yum:
      name: "{{ item }}"
      state: present
  with_items:
      - mysql-community-server
      - mysql-community-client
      - MySQL-python
  when: mysql_install and (ansible_distribution == "CentOS" or ansible_distribution == "Redhat")

- name: Adjust MySQL Configuration File
  become: yes
  lineinfile:
      dest: /etc/my.cnf
      line: "{{ item }}"
  with_items:
      - "character-set-server=utf8"
      - "bind-address=*"
      - "lower_case_table_names=1"
  when: mysql_install and (ansible_distribution == "CentOS" or ansible_distribution == "Redhat")

- name: Copy Password Capture Script
  become: yes
  copy:
      src: files/extract-password.sh
      dest: /tmp/extract-password.sh
      mode: 0555
  when: mysql_install and (ansible_distribution == "CentOS" or ansible_distribution == "Redhat")

- name: Copy Password Alter Script
  become: yes
  copy:
      src: files/change-password.sh
      dest: /tmp/change-password.sh
      mode: 0555
  when: mysql_install and (ansible_distribution == "CentOS" or ansible_distribution == "Redhat")

- name: Start MySQL
  become: yes
  systemd:
      name: mysqld
      enabled: yes
      daemon_reload: yes
      state: restarted
  when: mysql_install

- name: Capture MySQL Root Password
  become: yes
  shell: /tmp/extract-password.sh
  register: password
  when: mysql_install and (ansible_distribution == "CentOS" or ansible_distribution == "Redhat")

- debug:
      msg: "Password = {{ password.stdout }}"
  when: mysql_install

# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (5.7.x).
  command: "/tmp/change-password.sh {{ password.stdout }}"
  when: mysql_install
